plugins {
    id 'com.android.application' version '8.5.2'
    id 'org.jetbrains.kotlin.android' version '2.0.0'
}

android {
    namespace 'example.fixture'
    compileSdk 35
    defaultConfig {
        applicationId 'example.fixture'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
